# AUTO-GENERATED by Auto-Quant Factory
# Source strategy: MeanReversion_v1
# Do not edit manually — re-run Auto-Quant to regenerate.

import talib.abstract as ta
import pandas as pd
from freqtrade.strategy import IStrategy


class MeanReversion_v1_Optimized(IStrategy):

    def custom_stoploss(self, pair: str, trade, current_time, current_rate: float,
                        current_profit: float, after_fill: bool, **kwargs) -> float | None:
        """Three-tier aggressive trailing stoploss with profit lock-in.
        
        Tier 1: If profit >= 2%, lock stoploss at +0.5%
        Tier 2: If profit >= 4%, lock stoploss at +1.5%
        Tier 3: If profit >= 8%, lock stoploss at +3.0%
        """
        from freqtrade.strategy import stoploss_from_open
        
        if current_profit >= 0.08:  # 8%
            return stoploss_from_open(0.03, current_profit, is_short=trade.is_short, leverage=trade.leverage) or 1
        if current_profit >= 0.04:  # 4%
            return stoploss_from_open(0.015, current_profit, is_short=trade.is_short, leverage=trade.leverage) or 1
        if current_profit >= 0.02:  # 2%
            return stoploss_from_open(0.005, current_profit, is_short=trade.is_short, leverage=trade.leverage) or 1
        return None

    INTERFACE_VERSION = 3
    timeframe = "5m"

    minimal_roi = {"0": 0.247, "23": 0.058, "72": 0.022, "190": 0.0}
    stoploss = -0.13
    max_open_trades = 5

    def populate_indicators(self, dataframe: pd.DataFrame, metadata: dict) -> pd.DataFrame:
        dataframe['rsi'] = ta.RSI(dataframe, timeperiod=14)
        dataframe['ema2000'] = ta.EMA(dataframe, timeperiod=2000)
        return dataframe

    def populate_entry_trend(self, dataframe: pd.DataFrame, metadata: dict) -> pd.DataFrame:
        dataframe.loc[
            (dataframe['rsi'] < 22) &
            (dataframe['close'] > dataframe['ema2000']),
            'enter_long'] = 1
        return dataframe

    def populate_exit_trend(self, dataframe: pd.DataFrame, metadata: dict) -> pd.DataFrame:
        dataframe['exit_long'] = 0
        return dataframe






