#!/usr/bin/env python3
"""
Generate a profitable trading strategy using genetic algorithm evolution
with actual Freqtrade backtesting.
"""

import sys
sys.path.insert(0, 'backend')

import asyncio
import json
import numpy as np
import subprocess
from pathlib import Path

from services.auto_quant.genetic.genetic_evolution import run_genetic_evolution, GAConfig
from services.auto_quant.genetic.strategy_dna import get_default_indicator_names


async def freqtrade_backtest(dna):
    """Run actual Freqtrade backtest with DNA parameters."""
    
    # Extract parameters from DNA
    buy_thresholds = dna.buy_thresholds
    sell_thresholds = dna.sell_thresholds
    risk_params = dna.risk_parameters
    hold_days = dna.hold_days
    
    # Generate strategy file with DNA parameters
    strategy_file = generate_strategy_from_dna(dna)
    
    # Run Freqtrade backtest
    try:
        result = subprocess.run(
            ["freqtrade", "backtesting", "-c", "user_data/config.json"],
            capture_output=True,
            text=True,
            timeout=300
        )
        
        # Parse backtest results
        output = result.stdout
        if "Total profit %" in output:
            # Extract profit percentage
            for line in output.split('\n'):
                if "Total profit %" in line:
                    profit_str = line.split('|')[-1].strip()
                    try:
                        profit_pct = float(profit_str.replace('%', ''))
                        break
                    except:
                        profit_pct = 0.0
        else:
            profit_pct = 0.0
        
        # Extract trade count
        if "Total/Daily Avg Trades" in output:
            for line in output.split('\n'):
                if "Total/Daily Avg Trades" in line:
                    trades_str = line.split('|')[1].strip()
                    try:
                        total_trades = int(trades_str.split('/')[0].strip())
                        break
                    except:
                        total_trades = 0
        else:
            total_trades = 0
        
        return {
            "sharpe_ratio": 0.0,  # Would need to parse from output
            "profit_total": profit_pct,
            "max_drawdown_abs": 0.0,
            "profit_factor": 0.0,
            "win_rate": 0.0,
            "total_trades": total_trades,
        }
        
    except subprocess.TimeoutExpired:
        print("Backtest timed out")
        return {
            "sharpe_ratio": 0.0,
            "profit_total": -100.0,
            "max_drawdown_abs": 1.0,
            "profit_factor": 0.0,
            "win_rate": 0.0,
            "total_trades": 0,
        }
    except Exception as e:
        print(f"Backtest error: {e}")
        return {
            "sharpe_ratio": 0.0,
            "profit_total": -100.0,
            "max_drawdown_abs": 1.0,
            "profit_factor": 0.0,
            "win_rate": 0.0,
            "total_trades": 0,
        }


def generate_strategy_from_dna(dna):
    """Generate Freqtrade strategy file from DNA."""
    
    strategy_file = Path("user_data/strategies/GAProfitableStrategy.py")
    
    # Extract parameters from DNA
    buy_thresholds = dna.buy_thresholds
    sell_thresholds = dna.sell_thresholds
    risk_params = dna.risk_parameters
    hold_days = dna.hold_days
    
    strategy_code = f'''"""
Profitable strategy generated by Genetic Algorithm evolution.
"""

from freqtrade.strategy import IStrategy
from pandas import DataFrame
import talib.abstract as ta


class GAProfitableStrategy(IStrategy):
    """
    Profitable trading strategy evolved using genetic algorithms.
    """
    
    # Strategy interface version
    INTERFACE_VERSION = 3
    
    # Minimal ROI designed for the strategy
    minimal_roi = {{
        "0": 0.02,  # 2% profit
        "120": 0.015,  # 1.5% profit after 5 days
        "240": 0.01,  # 1% profit after 10 days
    }}
    
    # Stoploss
    stoploss = -0.025
    
    # Trailing stop
    trailing_stop = False
    
    # Optimal timeframe
    timeframe = '4h'
    
    # Run "populate_indicators" only for new candle.
    process_only_new_candles = False
    
    # These values can be overridden in the "ask_strategy" section in the config.
    use_exit_signal = True
    exit_profit_only = False
    ignore_roi_if_exit_signal = False
    
    # Number of candles the strategy requires before producing valid signals
    startup_candle_count: int = 30
    
    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """
        Populate technical indicators.
        """
        
        # RSI
        dataframe['rsi'] = ta.RSI(dataframe, timeperiod=14)
        
        # MACD
        macd = ta.MACD(dataframe)
        dataframe['macd'] = macd['macd']
        dataframe['macdsignal'] = macd['macdsignal']
        
        # EMA
        dataframe['ema_20'] = ta.EMA(dataframe, timeperiod=20)
        dataframe['ema_50'] = ta.EMA(dataframe, timeperiod=50)
        
        # ATR
        dataframe['atr'] = ta.ATR(dataframe, timeperiod=14)
        
        # Bollinger Bands using talib
        dataframe['bb_upperband'], dataframe['bb_middleband'], dataframe['bb_lowerband'] = ta.BBANDS(
            dataframe, timeperiod=20, nbdevup=2.0, nbdevdn=2.0
        )
        
        return dataframe
    
    def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """
        Populate buy signals based on DNA thresholds.
        """
        
        dataframe.loc[
            (
                (dataframe['rsi'] < {buy_thresholds['rsi_buy']}) &
                (dataframe['macd'] > dataframe['macdsignal'])
            ),
            'buy'
        ] = 1
        
        return dataframe
    
    def populate_sell_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """
        Populate sell signals based on DNA thresholds.
        """
        
        dataframe.loc[
            (
                (dataframe['rsi'] > {sell_thresholds['rsi_sell']}) |
                (dataframe['macd'] < dataframe['macdsignal'])
            ),
            'sell'
        ] = 1
        
        return dataframe
'''
    
    # Write strategy file
    with open(strategy_file, "w") as f:
        f.write(strategy_code)
    
    return strategy_file


async def generate_strategy():
    """Generate profitable strategy using GA with real backtesting."""
    
    print("=" * 60)
    print("PROFITABLE STRATEGY GENERATOR WITH REAL BACKTESTING")
    print("=" * 60)
    
    # Get indicator names
    indicator_names = get_default_indicator_names()[:10]
    print(f"Using {len(indicator_names)} indicators")
    
    # Create GA configuration
    config = GAConfig(
        population_size=10,  # Smaller population for faster iteration
        generations=5,  # Fewer generations for faster iteration
        elite_size=2,
        tournament_size=3,
        crossover_rate=0.8,
        mutation_rate=0.1,
        mutation_strength=0.1,
        adaptive_mutation=True,
    )
    
    print(f"GA config: population={config.population_size}, generations={config.generations}")
    
    # Run genetic evolution with real backtesting
    print("\nStarting genetic evolution with real Freqtrade backtesting...")
    result = await run_genetic_evolution(
        backtest_func=freqtrade_backtest,
        config=config,
        indicator_names=indicator_names,
    )
    
    # Print results
    print("\n" + "=" * 60)
    print("GENETIC EVOLUTION RESULTS")
    print("=" * 60)
    print(f"Best fitness: {result.best_fitness:.4f}")
    print(f"Converged: {result.converged}")
    print(f"Total evaluations: {result.total_evaluations}")
    print(f"Elapsed time: {result.elapsed_seconds:.2f} seconds")
    
    # Check profitability
    is_profitable = result.best_fitness > 0.5 and result.best_fitness_result.total_return > 20
    print(f"\nProfitable: {is_profitable}")
    
    if is_profitable:
        print("\n✓ Profitable strategy discovered!")
        
        # Save best DNA
        output_dir = Path("user_data/strategies")
        output_dir.mkdir(parents=True, exist_ok=True)
        
        dna_file = output_dir / "best_strategy_dna.json"
        dna_dict = result.best_dna.to_dict()
        
        # Convert numpy types to Python native types for JSON serialization
        def convert_numpy(obj):
            if isinstance(obj, dict):
                return {k: convert_numpy(v) for k, v in obj.items()}
            elif isinstance(obj, list):
                return [convert_numpy(v) for v in obj]
            elif isinstance(obj, (np.bool_, bool)):
                return bool(obj)
            elif isinstance(obj, (np.integer, int)):
                return int(obj)
            elif isinstance(obj, (np.floating, float)):
                return float(obj)
            else:
                return obj
        
        dna_dict = convert_numpy(dna_dict)
        
        with open(dna_file, "w") as f:
            json.dump(dna_dict, f, indent=2)
        print(f"Best DNA saved to: {dna_file}")
        
        # Generate final strategy file
        strategy_file = generate_strategy_from_dna(result.best_dna)
        print(f"Freqtrade strategy saved to: {strategy_file}")
        
        return result.best_dna, strategy_file
    else:
        print("\n✗ No profitable strategy found")
        return None, None


async def main():
    """Main entry point."""
    
    best_dna, strategy_file = await generate_strategy()
    
    if strategy_file:
        print(f"\n✓ Strategy file created: {strategy_file}")
        return 0
    else:
        print("\nFailed to generate profitable strategy")
        return 1


if __name__ == "__main__":
    exit_code = asyncio.run(main())
    sys.exit(exit_code)
