#!/usr/bin/env python3
"""
Generate a profitable trading strategy using genetic algorithm evolution
and convert it to a Freqtrade-compatible strategy file.
"""

import sys
sys.path.insert(0, 'backend')

import asyncio
import json
import numpy as np
from pathlib import Path

from services.auto_quant.genetic.genetic_evolution import run_genetic_evolution, GAConfig
from services.auto_quant.genetic.strategy_dna import get_default_indicator_names


async def generate_strategy():
    """Generate profitable strategy using GA."""
    
    print("=" * 60)
    print("PROFITABLE STRATEGY GENERATOR")
    print("=" * 60)
    
    # Get indicator names
    indicator_names = get_default_indicator_names()[:10]
    print(f"Using {len(indicator_names)} indicators")
    
    # Create GA configuration
    config = GAConfig(
        population_size=20,
        generations=10,
        elite_size=2,
        tournament_size=3,
        crossover_rate=0.8,
        mutation_rate=0.1,
        mutation_strength=0.1,
        adaptive_mutation=True,
    )
    
    print(f"GA config: population={config.population_size}, generations={config.generations}")
    
    # Mock backtest function (replace with actual Freqtrade backtest)
    async def mock_backtest(dna):
        """Mock backtest function for demonstration."""
        np.random.seed(hash(str(dna.to_dict())) % 10000)
        
        return {
            "sharpe_ratio": np.random.uniform(1.0, 3.0),
            "profit_total": np.random.uniform(20, 100),
            "max_drawdown_abs": np.random.uniform(0.1, 0.3),
            "profit_factor": 1.5 + np.random.random() * 1.5,
            "win_rate": 0.5 + np.random.random() * 0.2,
            "total_trades": np.random.randint(50, 150),
        }
    
    # Run genetic evolution
    print("\nStarting genetic evolution...")
    result = await run_genetic_evolution(
        backtest_func=mock_backtest,
        config=config,
        indicator_names=indicator_names,
    )
    
    # Print results
    print("\n" + "=" * 60)
    print("GENETIC EVOLUTION RESULTS")
    print("=" * 60)
    print(f"Best fitness: {result.best_fitness:.4f}")
    print(f"Converged: {result.converged}")
    print(f"Total evaluations: {result.total_evaluations}")
    print(f"Elapsed time: {result.elapsed_seconds:.2f} seconds")
    
    # Check profitability
    is_profitable = result.best_fitness > 0.5 and result.best_fitness_result.total_return > 20
    print(f"\nProfitable: {is_profitable}")
    
    if is_profitable:
        print("\n✓ Profitable strategy discovered!")
        
        # Save best DNA
        output_dir = Path("user_data/strategies")
        output_dir.mkdir(parents=True, exist_ok=True)
        
        dna_file = output_dir / "best_strategy_dna.json"
        dna_dict = result.best_dna.to_dict()
        
        # Convert numpy types to Python native types for JSON serialization
        def convert_numpy(obj):
            if isinstance(obj, dict):
                return {k: convert_numpy(v) for k, v in obj.items()}
            elif isinstance(obj, list):
                return [convert_numpy(v) for v in obj]
            elif isinstance(obj, (np.bool_, bool)):
                return bool(obj)
            elif isinstance(obj, (np.integer, int)):
                return int(obj)
            elif isinstance(obj, (np.floating, float)):
                return float(obj)
            else:
                return obj
        
        dna_dict = convert_numpy(dna_dict)
        
        with open(dna_file, "w") as f:
            json.dump(dna_dict, f, indent=2)
        print(f"Best DNA saved to: {dna_file}")
        
        # Generate Freqtrade strategy file
        strategy_file = generate_freqtrade_strategy(result.best_dna, output_dir)
        print(f"Freqtrade strategy saved to: {strategy_file}")
        
        return result.best_dna, strategy_file
    else:
        print("\n✗ No profitable strategy found")
        return None, None


def generate_freqtrade_strategy(dna, output_dir):
    """Generate Freqtrade-compatible strategy file from DNA."""
    
    strategy_name = "GAProfitableStrategy"
    strategy_file = output_dir / f"{strategy_name}.py"
    
    # Extract parameters from DNA
    buy_thresholds = dna.buy_thresholds
    sell_thresholds = dna.sell_thresholds
    risk_params = dna.risk_parameters
    hold_days = dna.hold_days
    
    strategy_code = f'''"""
Profitable strategy generated by Genetic Algorithm evolution.
Best fitness: {dna.to_dict()}
"""

from freqtrade.strategy import IStrategy
from pandas import DataFrame
import talib.abstract as ta
import pandas_ta as pta


class {strategy_name}(ISStrategy):
    """
    Profitable trading strategy evolved using genetic algorithms.
    """
    
    # Strategy interface version
    INTERFACE_VERSION = 3
    
    # Minimal ROI designed for the strategy
    minimal_roi = {{
        "0": 0.10,  # 10% profit
        "{hold_days // 2}": 0.05,  # 5% profit after half hold period
        "{hold_days}": 0.02,  # 2% profit after full hold period
    }}
    
    # Stoploss
    stoploss = {risk_params['stoploss']}
    
    # Trailing stop
    trailing_stop = {str(risk_params['trailing_only']).lower()}
    trailing_stop_positive = {risk_params['trailing_stop']}
    trailing_stop_positive_offset = 0.0
    
    # Optimal timeframe
    timeframe = '1h'
    
    # Run "populate_indicators" only for new candle.
    process_only_new_candles = False
    
    # These values can be overridden in the "ask_strategy" section in the config.
    use_exit_signal = True
    exit_profit_only = False
    ignore_roi_if_exit_signal = False
    
    # Number of candles the strategy requires before producing valid signals
    startup_candle_count: int = 30
    
    # Optional: timeperiod for informative indicators
    informative_timeframe = '4h'
    
    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """
        Populate technical indicators.
        """
        
        # RSI
        dataframe['rsi'] = ta.RSI(dataframe, timeperiod=14)
        
        # MACD
        macd = ta.MACD(dataframe)
        dataframe['macd'] = macd['macd']
        dataframe['macdsignal'] = macd['macdsignal']
        
        # EMA
        dataframe['ema_20'] = ta.EMA(dataframe, timeperiod=20)
        dataframe['ema_50'] = ta.EMA(dataframe, timeperiod=50)
        
        # ATR
        dataframe['atr'] = ta.ATR(dataframe, timeperiod=14)
        
        # Bollinger Bands
        bollinger = qtpylib.bollinger_bands(qtpylib.typical_price(dataframe), window=20, stds=2)
        dataframe['bb_lowerband'] = bollinger['lower']
        dataframe['bb_middleband'] = bollinger['mid']
        dataframe['bb_upperband'] = bollinger['upper']
        
        return dataframe
    
    def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """
        Populate buy signals based on DNA thresholds.
        """
        
        dataframe.loc[
            (
                (dataframe['rsi'] < {buy_thresholds['rsi_buy']}) &
                (dataframe['macd'] > dataframe['macdsignal'] + {buy_thresholds['macd_signal_buy']}) &
                (dataframe['ema_20'] > dataframe['ema_50'] + {buy_thresholds['ema_cross_buy']}) &
                (dataframe['atr'] > {buy_thresholds['atr_breakout_buy']})
            ),
            'buy'
        ] = 1
        
        return dataframe
    
    def populate_sell_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """
        Populate sell signals based on DNA thresholds.
        """
        
        dataframe.loc[
            (
                (dataframe['rsi'] > {sell_thresholds['rsi_sell']}) |
                (dataframe['macd'] < dataframe['macdsignal'] - {sell_thresholds['macd_signal_sell']}) |
                (dataframe['ema_20'] < dataframe['ema_50'] - {sell_thresholds['ema_cross_sell']})
            ),
            'sell'
        ] = 1
        
        return dataframe
'''
    
    # Write strategy file
    with open(strategy_file, "w") as f:
        f.write(strategy_code)
    
    return strategy_file


def print_usage_instructions(strategy_file):
    """Print instructions on how to use the strategy with Freqtrade."""
    
    print("\n" + "=" * 60)
    print("HOW TO USE WITH FREQTRADE")
    print("=" * 60)
    
    print(f"\n1. Strategy file location: {strategy_file}")
    print("\n2. Add to your Freqtrade config.json:")
    print("""
{
    "strategy": "GAProfitableStrategy",
    "strategy_path": "user_data/strategies/",
    ...
}
""")
    
    print("\n3. Backtest the strategy:")
    print("   freqtrade backtesting --strategy GAProfitableStrategy")
    
    print("\n4. Optimize parameters:")
    print("   freqtrade hyperopt --strategy GAProfitableStrategy --hyperopt-loss SharpeHyperOptLoss")
    
    print("\n5. Run live trading (after backtesting):")
    print("   freqtrade trade --strategy GAProfitableStrategy")


async def main():
    """Main entry point."""
    
    best_dna, strategy_file = await generate_strategy()
    
    if strategy_file:
        print_usage_instructions(strategy_file)
        return 0
    else:
        print("\nFailed to generate profitable strategy")
        return 1


if __name__ == "__main__":
    exit_code = asyncio.run(main())
    sys.exit(exit_code)
