/**
 * Mock PipelineState for a failed AutoQuant run with generalization_failure
 * Used for testing the premium pipeline UI with failure scenarios
 */
export const mockPipelineStateFailure = {
  status: "failed",
  run_id: "test-run-789",
  started_at: "2024-01-01T12:00:00Z",
  completed_at: "2024-01-01T12:10:00Z",
  current_stage: 4,
  progress: 65,
  progress_percent: 65,
  stages: [
    {
      index: 0,
      name: "Pre-Flight Filtering",
      status: "passed",
      message: "Strategy validation completed successfully",
      data: {
        validation_time: 2.1,
        error_count: 0,
        warnings_found: 0,
      },
      started_at: "2024-01-01T12:00:00Z",
      duration_s: 2.1,
    },
    {
      index: 1,
      name: "Portfolio Baseline Backtest",
      status: "passed",
      message: "Baseline backtest completed",
      data: {
        total_profit: 0.12,
        max_drawdown_pct: 15.3,
        trade_count: 198,
        win_rate: 51.2,
      },
      started_at: "2024-01-01T12:00:05Z",
      duration_s: 42.5,
    },
    {
      index: 2,
      name: "WFA Hyperopt",
      status: "passed",
      message: "Hyperopt optimization completed",
      data: {
        best_parameters: { roi: "0.025", stoploss: "-0.06" },
        improvement_pct: 18.2,
        optimization_epochs: 120,
        wfo_windows: 4,
      },
      started_at: "2024-01-01T12:01:00Z",
      duration_s: 165.3,
    },
    {
      index: 3,
      name: "Robustness & Feature Injection",
      status: "passed",
      message: "Robustness checks passed",
      data: {
        robustness_score: 0.72,
        features_added: 2,
        stability_score: 0.65,
      },
      started_at: "2024-01-01T12:04:00Z",
      duration_s: 55.8,
    },
    {
      index: 4,
      name: "Portfolio Competition",
      status: "failed",
      message: "Strategy failed out-of-sample validation",
      data: {
        competition_score: 0.35,
        rank_position: 5,
        advantage_margin: -0.12,
        errors: ["OOS profit below threshold", "Max drawdown exceeded limit"],
        warnings: ["Low win rate in OOS period"],
      },
      started_at: "2024-01-01T12:05:00Z",
      duration_s: 120.5,
    },
    {
      index: 5,
      name: "Delivery",
      status: "pending",
      message: "",
      data: {},
      started_at: null,
      duration_s: null,
    },
  ],
  wfo_windows: [],
  recent_events: [],
  generalization_failure: {
    reason: "robustness_failed",
    thresholds: {
      min_oos_profit: 0.02,
      max_drawdown_threshold: 25,
    },
    attempts: [
      {
        attempt: 1,
        label: "Attempt 1",
        loss: "SharpeHyperOptLoss",
        spaces: ["buy", "sell", "roi", "stoploss"],
        profit: 0.015,
        drawdown: 28.5,
        trades: 156,
        reason: "drawdown",
        ollama_suggestions: {
          reasoning: "Strategy shows excessive drawdown in OOS period. Consider tightening stop-loss or reducing position size.",
          hyperopt_loss: "CalmarHyperOptLoss",
          hyperopt_spaces: ["buy", "sell", "stoploss"],
          hyperopt_epochs: 200,
        },
      },
      {
        attempt: 2,
        label: "Attempt 2",
        loss: "CalmarHyperOptLoss",
        spaces: ["buy", "sell", "stoploss"],
        profit: 0.018,
        drawdown: 26.2,
        trades: 142,
        reason: "drawdown",
      },
    ],
    best_attempt: {
      attempt: 2,
      label: "Attempt 2",
      loss: "CalmarHyperOptLoss",
      spaces: ["buy", "sell", "stoploss"],
      profit: 0.018,
      drawdown: 26.2,
      trades: 142,
      reason: "drawdown",
    },
    best_attempt_file: "AIStrategy_Optimized_v2.py",
    best_attempt_strategy_name: "OptimizedStrategy_v2",
    suggestions: [
      "Extend in-sample date range to capture more market regimes",
      "Enable trading window filters to avoid volatile periods",
      "Select different strategy type (e.g., trend-following vs mean-reversion)",
      "Reduce position size to lower drawdown exposure",
    ],
  },
  retry_history: [
    {
      attempt: 1,
      status: "failed",
      error_code: "drawdown",
      action: "tighten_stoploss",
      reason: "Max drawdown exceeded 25% threshold",
      timestamp: "2024-01-01T12:06:30Z",
      metrics_before: { max_drawdown: 28.5, profit: 0.015 },
      metrics_after: { max_drawdown: 26.2, profit: 0.018 },
      before: { stoploss: -0.05 },
      after: { stoploss: -0.04 },
    },
  ],
};
