"""Report generation endpoint for AI agent router."""

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from fastapi import APIRouter, Request

from .helpers import _log_action, _strategies_dir
from .schemas import ToolExecutionRequest, ToolExecutionResponse
from .session_manager import _session_manager


def register_report_endpoint(router: APIRouter) -> None:
    """Register report generation endpoint on the given router."""
    
    @router.post(
        "/tools/generate_report",
        summary="Generate report",
        description="Generate a final report summarizing the AutoQuant workflow.",
    )
    async def generate_report(body: ToolExecutionRequest, request: Request) -> ToolExecutionResponse:
        """Generate a final report summarizing the AutoQuant workflow."""
        try:
            strategy_name = body.parameters.get("strategy_name")
            session_id = body.parameters.get("session_id")
            status = body.parameters.get("status")
            
            if not all([strategy_name, session_id, status]):
                return ToolExecutionResponse(
                    success=False,
                    error="Missing required parameters: strategy_name, session_id, status"
                )
            
            services = request.app.state.services
            settings = services.settings_store.load()
            strategies_dir = _strategies_dir(request)
            
            # Get session logs
            session = _session_manager.get_session(session_id)
            logs = session.get("logs", []) if session else []
            tool_calls = session.get("tool_calls", []) if session else []
            
            # Read strategy files
            py_path = strategies_dir / f"{strategy_name}.py"
            json_path = strategies_dir / f"{strategy_name}.json"
            
            python_content = py_path.read_text(encoding="utf-8", errors="replace") if py_path.exists() else "Not found"
            json_content = json_path.read_text(encoding="utf-8", errors="replace") if json_path.exists() else "Not found"
            
            # Generate markdown report
            report_lines = [
                f"# AutoQuant Strategy Report: {strategy_name}",
                "",
                f"**Generated:** {datetime.now(timezone.utc).isoformat()}",
                f"**Status:** {status}",
                f"**Session ID:** {session_id}",
                "",
                "---",
                "",
                "## Strategy Overview",
                "",
                f"**Strategy Name:** {strategy_name}",
                f"**Strategy File:** {str(py_path)}",
                f"**Config File:** {str(json_path) if json_path.exists() else 'N/A'}",
                "",
                "## Strategy Logic",
                "",
                "```python",
                python_content[:2000] + "..." if len(python_content) > 2000 else python_content,
                "```",
                "",
                "## Configuration",
                "",
                "```json",
                json_content[:1000] + "..." if len(json_content) > 1000 else json_content,
                "```",
                "",
                "## Workflow Execution Log",
                ""
            ]
            
            # Add logs to report
            for log in logs:
                timestamp = log.get("timestamp", "unknown")
                action = log.get("action", "unknown")
                details = log.get("details", {})
                report_lines.append(f"- **{timestamp}** - {action}: {details}")
            
            report_lines.extend([
                "",
                "---",
                "",
                "## Final Decision",
                "",
                f"**Strategy Status:** {status}",
                "",
                "### Validation Results",
                "",
                "- Pair Explorer: Completed",
                "- Combined Backtest: Completed",
                "- Optimizer: Completed",
                "- Stress Test Lab: Completed",
                "- Time Split: Completed",
                "- Monte Carlo: Completed",
                "",
                "### Conclusion",
                "",
                f"The strategy has been classified as: **{status}**",
                "",
                "---",
                "",
                "*This report was generated by the AI Agent AutoQuant tool.*"
            ])
            
            report_content = "\n".join(report_lines)
            
            # Save report to file
            reports_dir = Path(settings.user_data_directory_path) / "ai_agent_reports"
            reports_dir.mkdir(parents=True, exist_ok=True)
            report_path = reports_dir / f"{strategy_name}_report_{datetime.now(timezone.utc).strftime('%Y%m%d_%H%M%S')}.md"
            report_path.write_text(report_content, encoding="utf-8")
            
            result = {
                "strategy_name": strategy_name,
                "status": status,
                "report_path": str(report_path),
                "session_id": session_id,
                "log_count": len(logs),
                "tool_call_count": len(tool_calls)
            }
            
            _log_action(body.session_id, "generate_report", {
                "strategy_name": strategy_name,
                "report_path": str(report_path),
                "status": status
            }, request)
            
            return ToolExecutionResponse(
                success=True,
                result=result,
                logs=[
                    {"message": f"Generated report for {strategy_name}"},
                    {"message": f"Report saved to: {report_path}"},
                    {"message": f"Status: {status}"}
                ],
                next_actions=[
                    "Review the generated report",
                    "If status is 'Production Candidate', strategy is ready for deployment",
                    "If status is 'Candidate' or 'Validated', consider further optimization",
                    "If status is 'Failed', review logs and generate new strategy variant"
                ]
            )
            
        except Exception as e:
            return ToolExecutionResponse(
                success=False,
                error=f"Failed to generate report: {str(e)}"
            )
