/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RunsNewRouteImport } from './routes/runs.new'
import { Route as RunsRunIdRouteImport } from './routes/runs.$runId'
import { Route as RunsRunIdIndexRouteImport } from './routes/runs.$runId.index'
import { Route as RunsRunIdResultsRouteImport } from './routes/runs.$runId.results'
import { Route as RunsRunIdPairsRouteImport } from './routes/runs.$runId.pairs'
import { Route as RunsRunIdChatRouteImport } from './routes/runs.$runId.chat'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsNewRoute = RunsNewRouteImport.update({
  id: '/runs/new',
  path: '/runs/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRunIdRoute = RunsRunIdRouteImport.update({
  id: '/runs/$runId',
  path: '/runs/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRunIdIndexRoute = RunsRunIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RunsRunIdRoute,
} as any)
const RunsRunIdResultsRoute = RunsRunIdResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => RunsRunIdRoute,
} as any)
const RunsRunIdPairsRoute = RunsRunIdPairsRouteImport.update({
  id: '/pairs',
  path: '/pairs',
  getParentRoute: () => RunsRunIdRoute,
} as any)
const RunsRunIdChatRoute = RunsRunIdChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => RunsRunIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/runs/$runId': typeof RunsRunIdRouteWithChildren
  '/runs/new': typeof RunsNewRoute
  '/runs/$runId/chat': typeof RunsRunIdChatRoute
  '/runs/$runId/pairs': typeof RunsRunIdPairsRoute
  '/runs/$runId/results': typeof RunsRunIdResultsRoute
  '/runs/$runId/': typeof RunsRunIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/runs/new': typeof RunsNewRoute
  '/runs/$runId/chat': typeof RunsRunIdChatRoute
  '/runs/$runId/pairs': typeof RunsRunIdPairsRoute
  '/runs/$runId/results': typeof RunsRunIdResultsRoute
  '/runs/$runId': typeof RunsRunIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/runs/$runId': typeof RunsRunIdRouteWithChildren
  '/runs/new': typeof RunsNewRoute
  '/runs/$runId/chat': typeof RunsRunIdChatRoute
  '/runs/$runId/pairs': typeof RunsRunIdPairsRoute
  '/runs/$runId/results': typeof RunsRunIdResultsRoute
  '/runs/$runId/': typeof RunsRunIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/runs/$runId'
    | '/runs/new'
    | '/runs/$runId/chat'
    | '/runs/$runId/pairs'
    | '/runs/$runId/results'
    | '/runs/$runId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/runs/new'
    | '/runs/$runId/chat'
    | '/runs/$runId/pairs'
    | '/runs/$runId/results'
    | '/runs/$runId'
  id:
    | '__root__'
    | '/'
    | '/runs/$runId'
    | '/runs/new'
    | '/runs/$runId/chat'
    | '/runs/$runId/pairs'
    | '/runs/$runId/results'
    | '/runs/$runId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RunsRunIdRoute: typeof RunsRunIdRouteWithChildren
  RunsNewRoute: typeof RunsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/new': {
      id: '/runs/new'
      path: '/runs/new'
      fullPath: '/runs/new'
      preLoaderRoute: typeof RunsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/$runId': {
      id: '/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/runs/$runId'
      preLoaderRoute: typeof RunsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/$runId/': {
      id: '/runs/$runId/'
      path: '/'
      fullPath: '/runs/$runId/'
      preLoaderRoute: typeof RunsRunIdIndexRouteImport
      parentRoute: typeof RunsRunIdRoute
    }
    '/runs/$runId/results': {
      id: '/runs/$runId/results'
      path: '/results'
      fullPath: '/runs/$runId/results'
      preLoaderRoute: typeof RunsRunIdResultsRouteImport
      parentRoute: typeof RunsRunIdRoute
    }
    '/runs/$runId/pairs': {
      id: '/runs/$runId/pairs'
      path: '/pairs'
      fullPath: '/runs/$runId/pairs'
      preLoaderRoute: typeof RunsRunIdPairsRouteImport
      parentRoute: typeof RunsRunIdRoute
    }
    '/runs/$runId/chat': {
      id: '/runs/$runId/chat'
      path: '/chat'
      fullPath: '/runs/$runId/chat'
      preLoaderRoute: typeof RunsRunIdChatRouteImport
      parentRoute: typeof RunsRunIdRoute
    }
  }
}

interface RunsRunIdRouteChildren {
  RunsRunIdChatRoute: typeof RunsRunIdChatRoute
  RunsRunIdPairsRoute: typeof RunsRunIdPairsRoute
  RunsRunIdResultsRoute: typeof RunsRunIdResultsRoute
  RunsRunIdIndexRoute: typeof RunsRunIdIndexRoute
}

const RunsRunIdRouteChildren: RunsRunIdRouteChildren = {
  RunsRunIdChatRoute: RunsRunIdChatRoute,
  RunsRunIdPairsRoute: RunsRunIdPairsRoute,
  RunsRunIdResultsRoute: RunsRunIdResultsRoute,
  RunsRunIdIndexRoute: RunsRunIdIndexRoute,
}

const RunsRunIdRouteWithChildren = RunsRunIdRoute._addFileChildren(
  RunsRunIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RunsRunIdRoute: RunsRunIdRouteWithChildren,
  RunsNewRoute: RunsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
